host: "127.0.0.1"
port: 12345
database_path: "/db.csv"
query_method: "GET"
backlog_number: 5
socket_package_size: 4096
data_separator: "dot"
environment: "HPC"
unit_conversion:
  cpu: 
    usage:
      milicpu: 1
      cputime: 2
      percentage: 3
  gpu: 
    usage: 
      percentage: 1
  mem: 
    Gb: 1
    Mb: 2
    Kb: 3
  frequency:
    GHz: 1
    MHz: 2
