process:
  frequency: 1
  requireRegister: false
  log_latency_flag: false
  latency_logging_path: "logs/"
  aggregator_host: "127.0.0.1"
  aggregator_port: 12345
  environment: "HPC"
system:
  frequency: 1
  requireRegister: false
  latency_logging_path: "logs/"
  log_latency_flag: false
  aggregator_host: "127.0.0.1"
  aggregator_port: 12345
  environment: "HPC"
exporter:
  host: "127.0.0.1"
  port: 8001
  environment: "HPC"
  node_aggregator:
    host: "127.0.0.1"
    port: 12345
    database_path: "/db.csv"
    query_method: "GET"
    backlog_number: 5
    socket_package_size: 4096
    data_separator: "dot"
    environment: "HPC"
    unit_conversion:
      cpu:
        usage:
          milicpu: 1
          cputime: 2
          percentage: 3
      gpu:
        usage:
          percentage: 1
      mem:
        Gb: 1
        Mb: 2
        Kb: 3
      frequency:
        GHz: 1
        MHz: 2
