process:
  metrics:
    - cpu_usage
    - gpu_usage
    - memory_used
  frequency: 1
  requireRegister: false
  request_url: "http://127.0.0.1:8000/metrics/process"
  logging_path: "/home/nguu0123/git/research/odop/odop_obs/logs/"
system:
  metrics:
    - cpu_usage
    - gpu_usage
    - memory_used
  frequency: 1
  requireRegister: false
  request_url: "http://127.0.0.1:8000/metrics/system"
  logging_path: "/home/nguu0123/git/research/odop/odop_obs/logs/"
exporter:
  unit_conversion:
    cpu: 
      usage:
        milicpu: 1
        cputime: 2
        percentage: 3
    gpu: 
      usage: 
        percentage: 1
    mem: 
      Gb: 1
      Mb: 2
      Kb: 3
    frequency:
      GHz: 1
      MHz: 2
node_aggregator:
  host: "127.0.0.1"
  port: 12345
  database_path: "/db.csv"
  thread_daemon: True
  query_method: "GET"
  backlog_number: 5
  socket_package_size: 4096
  data_separator: "dot"
